param(
  [string]$HexarchBaseUrl = "http://127.0.0.1:8099",
  [string]$AdminToken = "dev-token",
  [string]$ActorId = "admin",
  [string]$KeyName = "node-red-local",
  [string]$Description = "Node-RED single-user milestone key",
  [string[]]$Scopes = @("read", "write"),
  [string]$EnvOutPath = "./node-red/.env.node-red"
)

$ErrorActionPreference = "Stop"

$headers = @{ Authorization = "Bearer $AdminToken"; "X-Actor-Id" = $ActorId }

Write-Host "Creating API key '$KeyName' with scopes: $($Scopes -join ', ')"

$payload = @{
  name = $KeyName
  description = $Description
  tenant_id = $null
  org_id = $null
  scopes = $Scopes
} | ConvertTo-Json

# NOTE: /api-keys endpoints are disabled by default.
# Start the Hexarch API with either:
#   hexarch-ctl serve api --enable-api-key-admin
# or set:
#   HEXARCH_API_KEY_ADMIN_ENABLED=true

$resp = Invoke-RestMethod -Method POST -Uri "$HexarchBaseUrl/api-keys" -Headers $headers -ContentType "application/json" -Body $payload

if (-not $resp.token) {
  throw "Expected token in response, got: $($resp | ConvertTo-Json -Depth 6)"
}

$envText = @(
  "# Generated by scripts/node_red_setup.ps1",
  "HEXARCH_BASE_URL=http://host.docker.internal:8099",
  "HEXARCH_TOKEN=$($resp.token)"
) -join "`n"

$dir = Split-Path -Parent $EnvOutPath
if ($dir -and -not (Test-Path $dir)) {
  New-Item -ItemType Directory -Path $dir | Out-Null
}

Set-Content -Path $EnvOutPath -Value $envText -Encoding utf8
Write-Host "Wrote $EnvOutPath"
Write-Host "Token prefix: $($resp.token_prefix)"
